import "../formStyles.css"
import Navbar from "../../../components/navbar";
import Link from "next/link";
import { MessageCircle } from "lucide-react"; // nice chat icon

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    {children}
    
      <Link
        href="/dashboard/inbox"
        className="fixed bottom-6 right-6 bg-blue-600 hover:bg-blue-700 text-white p-4 rounded-full shadow-lg transition flex items-center justify-center"
      >
        <MessageCircle className="w-6 h-6" />
      </Link>
    </>   
  )
}
