import "../formStyles.css"
import Navbar from "../navbar";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <Navbar>
        
    </Navbar>
    {children}
    </>   
  )
}
